/***********************************************************************************
||   QUERY INFORMATION
||
||   Description: LOADS TABLE T_DM_EUE_CSP_BOH_MLY
||
||   CURRENT REVISION STANDARD:  v1.50
||
***********************************************************************************/
select
  F_ITEM_NO                 	 ,
  F_PRODUCT_DESC            	 ,
  F_EXTENDED_DESC           	 ,
  F_MAN_PART_NO             	 ,
  F_MRSP                    	 ,
  F_BUYER_CODE              	 ,
  F_STOCK_CODE              	 ,
  F_WHS_CODE                	 ,
  F_VENDOR_CODE             	 ,
  F_DESCRIPTION             	 ,
  F_VALID_SALES_CUST_CODE   	 ,
  F_CSP_TYPE                	 ,
  F_QUANTITYONHAND          	 ,
CASE
          WHEN F_QUANTITYONHAND <= F_QTY_AGE_1_3_MONTHS THEN F_QUANTITYONHAND
          WHEN F_QUANTITYONHAND > F_QTY_AGE_1_3_MONTHS THEN F_QTY_AGE_1_3_MONTHS
          ELSE 0
       END
          F_QTY_AGE_1_3_MONTHS,
       CASE
       WHEN (F_QUANTITYONHAND <= F_QTY_AGE_1_3_MONTHS)
          THEN
             0
          WHEN (F_QUANTITYONHAND >=
                   (F_QTY_AGE_1_3_MONTHS + F_QTY_AGE_4_6_MONTHS))
          THEN
             F_QTY_AGE_4_6_MONTHS
          WHEN (    F_QUANTITYONHAND > F_QTY_AGE_1_3_MONTHS
                AND F_QUANTITYONHAND <
                       (F_QTY_AGE_1_3_MONTHS + F_QTY_AGE_4_6_MONTHS))
          THEN
             F_QUANTITYONHAND - F_QTY_AGE_1_3_MONTHS
          ELSE
             0
       END
          F_QTY_AGE_4_6_MONTHS,
       CASE
       WHEN (F_QUANTITYONHAND <= F_QTY_AGE_1_3_MONTHS) then 0
       WHEN (F_QUANTITYONHAND <= F_QTY_AGE_1_3_MONTHS + F_QTY_AGE_4_6_MONTHS)
          THEN
             0
          WHEN (F_QUANTITYONHAND >=
                   (  F_QTY_AGE_1_3_MONTHS
                    + F_QTY_AGE_4_6_MONTHS
                    + F_QTY_AGE_7_9_MONTHS))
          THEN
             F_QTY_AGE_7_9_MONTHS
          WHEN (    F_QUANTITYONHAND >
                       (F_QTY_AGE_1_3_MONTHS + F_QTY_AGE_4_6_MONTHS)
                AND F_QUANTITYONHAND <
                       (  F_QTY_AGE_1_3_MONTHS
                        + F_QTY_AGE_4_6_MONTHS
                        + F_QTY_AGE_7_9_MONTHS))
          THEN
             F_QUANTITYONHAND - (F_QTY_AGE_1_3_MONTHS + F_QTY_AGE_4_6_MONTHS)
          ELSE
             0
       END
          F_QTY_AGE_7_9_MONTHS	 ,
         CASE
         WHEN (F_QUANTITYONHAND <= F_QTY_AGE_1_3_MONTHS) then 0
       WHEN (F_QUANTITYONHAND <= F_QTY_AGE_1_3_MONTHS + F_QTY_AGE_4_6_MONTHS)
          THEN
             0
         WHEN (F_QUANTITYONHAND <= F_QTY_AGE_1_3_MONTHS + F_QTY_AGE_4_6_MONTHS+F_QTY_AGE_7_9_MONTHS)
          THEN
             0
          WHEN (F_QUANTITYONHAND >=
                   (  F_QTY_AGE_1_3_MONTHS
                    + F_QTY_AGE_4_6_MONTHS
                    + F_QTY_AGE_7_9_MONTHS
                    +F_QTY_AGE_10_12_MONTHS))
          THEN
             F_QTY_AGE_10_12_MONTHS
          WHEN (    F_QUANTITYONHAND >
                       (F_QTY_AGE_1_3_MONTHS + F_QTY_AGE_4_6_MONTHS+F_QTY_AGE_7_9_MONTHS)
                AND F_QUANTITYONHAND <
                       (  F_QTY_AGE_1_3_MONTHS
                        + F_QTY_AGE_4_6_MONTHS
                        + F_QTY_AGE_7_9_MONTHS
                        +F_QTY_AGE_10_12_MONTHS))
          THEN
             F_QUANTITYONHAND - (F_QTY_AGE_1_3_MONTHS + F_QTY_AGE_4_6_MONTHS+F_QTY_AGE_7_9_MONTHS)
          ELSE
             0
       END
          F_QTY_AGE_10_12_MONTHS	 ,
     case
          WHEN (F_QUANTITYONHAND <= F_QTY_AGE_1_3_MONTHS) then 0
       WHEN (F_QUANTITYONHAND <= F_QTY_AGE_1_3_MONTHS + F_QTY_AGE_4_6_MONTHS)
          THEN
             0
         WHEN (F_QUANTITYONHAND <= F_QTY_AGE_1_3_MONTHS + F_QTY_AGE_4_6_MONTHS+F_QTY_AGE_7_9_MONTHS)
          THEN
             0
         WHEN (F_QUANTITYONHAND <= F_QTY_AGE_1_3_MONTHS + F_QTY_AGE_4_6_MONTHS+F_QTY_AGE_7_9_MONTHS +F_QTY_AGE_10_12_MONTHS)
          THEN
             0
     WHEN F_QUANTITYONHAND > (F_QTY_AGE_1_3_MONTHS + F_QTY_AGE_4_6_MONTHS+F_QTY_AGE_7_9_MONTHS+F_QTY_AGE_10_12_MONTHS)
     THEN F_QUANTITYONHAND - (F_QTY_AGE_1_3_MONTHS + F_QTY_AGE_4_6_MONTHS+F_QTY_AGE_7_9_MONTHS+F_QTY_AGE_10_12_MONTHS)
          ELSE 0
       END
          F_QTY_AGE_OVER_12_MONTHS,
  F_QTYREC01MONTHAGO        	 ,
  F_QTYREC02MONTHSAGO       	 ,
  F_QTYREC03MONTHSAGO       	 ,
  F_QTYREC04MONTHSAGO       	 ,
  F_QTYREC05MONTHSAGO       	 ,
  F_QTYREC06MONTHSAGO       	 ,
  F_QTYREC07MONTHSAGO       	 ,
  F_QTYREC08MONTHSAGO       	 ,
  F_QTYREC09MONTHSAGO       	 ,
  F_QTYREC10MONTHSAGO       	 ,
  F_QTYREC11MONTHSAGO       	 ,
  F_QTYREC12MONTHSAGO       	 ,
  F_QTYSOLD01MONTHAGO       	 ,
  F_QTYSOLD02MONTHSAGO      	 ,
  F_QTYSOLD03MONTHSAGO      	 ,
  F_QTYSOLD04MONTHSAGO      	 ,
  F_QTYSOLD05MONTHSAGO      	 ,
  F_QTYSOLD06MONTHSAGO      	 ,
  F_QTYSOLD07MONTHSAGO      	 ,
  F_QTYSOLD08MONTHSAGO      	 ,
  F_QTYSOLD09MONTHSAGO      	 ,
  F_QTYSOLD10MONTHSAGO      	 ,
  F_QTYSOLD11MONTHSAGO      	 ,
  F_QTYSOLD12MONTHSAGO      	,
  SYSDATE AS DW_LOAD_DATE,
         case when crncy_cc.F_SURROGATE_FK is not null then crncy_cc.F_SURROGATE_FK
         when crncy_vc.F_SURROGATE_FK is not null then crncy_vc.F_SURROGATE_FK
         else -99999 end F_CURRENCY_SK,
         TRUNC (SYSDATE) - 1 AS F_BUSINESS_DATE,
         INV_GROUP F_INV_GROUP,
         LOADED_AVERAGE_COST as F_LOADED_AVG_COST,
    SYSDATE AS      DW_MOD_DATE
from
(
select
ITEM_NO               	as	F_ITEM_NO               	 ,
PRODUCT_DESC          	as	F_PRODUCT_DESC          	 ,
EXTENDED_DESC         	as	F_EXTENDED_DESC         	 ,
MAN_PART_NO           	as	F_MAN_PART_NO           	 ,
MRSP                  	as	F_MRSP                  	 ,
F_CURRENCY_CODE         as  F_CURRENCY_CODE              ,
BUYER_CODE            	as	F_BUYER_CODE            	 ,
STOCK_CODE            	as	F_STOCK_CODE            	 ,
WHS_CODE              	as	F_WHS_CODE              	 ,
VENDOR_CODE           	as	F_VENDOR_CODE           	 ,
DESCRIPTION           	as	F_DESCRIPTION           	 ,
VALID_SALES_CUST_CODE 	as	F_VALID_SALES_CUST_CODE 	 ,
CSP_TYPE              	as	F_CSP_TYPE              	 ,
QUANTITYONHAND        	as	F_QUANTITYONHAND        	 ,
 (QTYREC01MONTHAGO+QTYREC02MONTHSAGO+QTYREC03MONTHSAGO) F_QTY_AGE_1_3_MONTHS,
(QTYREC04MONTHSAGO+QTYREC05MONTHSAGO+QTYREC06MONTHSAGO) F_QTY_AGE_4_6_MONTHS,
(QTYREC07MONTHSAGO+ QTYREC08MONTHSAGO+ QTYREC09MONTHSAGO) F_QTY_AGE_7_9_MONTHS,
(QTYREC10MONTHSAGO+QTYREC11MONTHSAGO+QTYREC12MONTHSAGO) F_QTY_AGE_10_12_MONTHS,
QTYREC01MONTHAGO      	as	F_QTYREC01MONTHAGO      	 ,
QTYREC02MONTHSAGO     	as	F_QTYREC02MONTHSAGO     	 ,
QTYREC03MONTHSAGO     	as	F_QTYREC03MONTHSAGO     	 ,
QTYREC04MONTHSAGO     	as	F_QTYREC04MONTHSAGO     	 ,
QTYREC05MONTHSAGO     	as	F_QTYREC05MONTHSAGO     	 ,
QTYREC06MONTHSAGO     	as	F_QTYREC06MONTHSAGO     	 ,
QTYREC07MONTHSAGO     	as	F_QTYREC07MONTHSAGO     	 ,
QTYREC08MONTHSAGO     	as	F_QTYREC08MONTHSAGO     	 ,
QTYREC09MONTHSAGO     	as	F_QTYREC09MONTHSAGO     	 ,
QTYREC10MONTHSAGO     	as	F_QTYREC10MONTHSAGO     	 ,
QTYREC11MONTHSAGO     	as	F_QTYREC11MONTHSAGO     	 ,
QTYREC12MONTHSAGO     	as	F_QTYREC12MONTHSAGO     	 ,
QTYSOLD01MONTHAGO     	as	F_QTYSOLD01MONTHAGO     	 ,
QTYSOLD02MONTHSAGO    	as	F_QTYSOLD02MONTHSAGO    	 ,
QTYSOLD03MONTHSAGO    	as	F_QTYSOLD03MONTHSAGO    	 ,
QTYSOLD04MONTHSAGO    	as	F_QTYSOLD04MONTHSAGO    	 ,
QTYSOLD05MONTHSAGO    	as	F_QTYSOLD05MONTHSAGO    	 ,
QTYSOLD06MONTHSAGO    	as	F_QTYSOLD06MONTHSAGO    	 ,
QTYSOLD07MONTHSAGO    	as	F_QTYSOLD07MONTHSAGO    	 ,
QTYSOLD08MONTHSAGO    	as	F_QTYSOLD08MONTHSAGO    	 ,
QTYSOLD09MONTHSAGO    	as	F_QTYSOLD09MONTHSAGO    	 ,
QTYSOLD10MONTHSAGO    	as	F_QTYSOLD10MONTHSAGO    	 ,
QTYSOLD11MONTHSAGO    	as	F_QTYSOLD11MONTHSAGO    	 ,
QTYSOLD12MONTHSAGO    	as	F_QTYSOLD12MONTHSAGO,
INV_GROUP,
LOADED_AVERAGE_COST
from
(select  a11.ITEM_NO  ITEM_NO,
  a11.PRODUCT_DESC  PRODUCT_DESC,
  a11.EXTENDED_DESC  EXTENDED_DESC,
  a11.MAN_PART_NO  MAN_PART_NO,
  a11.MRSP  MRSP,
  a11.currency_code  f_currency_code,
  a11.BUYER_CODE  BUYER_CODE,
  a11.STOCK_CODE  STOCK_CODE,
  a11.WHS_CODE  WHS_CODE,
  a11.VENDOR_CODE  VENDOR_CODE,
  a11.DESCRIPTION  DESCRIPTION,
  a11.cust_no VALID_SALES_CUST_CODE,
  A11.csp_type CSP_TYPE,
  sum(a11.QTY_ON_HAND)  QUANTITYONHAND,
  sum(a11.RCPT_QTY1)  QTYREC01MONTHAGO,
  sum(a11.RCPT_QTY2)  QTYREC02MONTHSAGO,
  sum(a11.RCPT_QTY3)  QTYREC03MONTHSAGO,
  sum(a11.RCPT_QTY4)  QTYREC04MONTHSAGO,
  sum(a11.RCPT_QTY5)  QTYREC05MONTHSAGO,
  sum(a11.RCPT_QTY6)  QTYREC06MONTHSAGO,
   sum(a11.RCPT_QTY7)  QTYREC07MONTHSAGO,
  sum(a11.RCPT_QTY8)  QTYREC08MONTHSAGO,
  sum(a11.RCPT_QTY9)  QTYREC09MONTHSAGO,
  sum(a11.RCPT_QTY10)  QTYREC10MONTHSAGO,
  sum(a11.RCPT_QTY11)  QTYREC11MONTHSAGO,
  sum(a11.RCPT_QTY12)  QTYREC12MONTHSAGO,
  sum(a11.SOLD_QTY1)  QTYSOLD01MONTHAGO,
  sum(a11.SOLD_QTY2)  QTYSOLD02MONTHSAGO,
  sum(a11.SOLD_QTY3)  QTYSOLD03MONTHSAGO,
  sum(a11.SOLD_QTY4)  QTYSOLD04MONTHSAGO,
  sum(a11.SOLD_QTY5)  QTYSOLD05MONTHSAGO,
  sum(a11.SOLD_QTY6)  QTYSOLD06MONTHSAGO,
  sum(a11.SOLD_QTY7)  QTYSOLD07MONTHSAGO,
  sum(a11.SOLD_QTY8)  QTYSOLD08MONTHSAGO,
  sum(a11.SOLD_QTY9)  QTYSOLD09MONTHSAGO,
  sum(a11.SOLD_QTY10)  QTYSOLD10MONTHSAGO,
  sum(a11.SOLD_QTY11)  QTYSOLD11MONTHSAGO,
  sum(a11.SOLD_QTY12)  QTYSOLD12MONTHSAGO,
  trim(a11.INV_GROUP) INV_GROUP,
  sum(a11.LOADED_AVERAGE_COST) LOADED_AVERAGE_COST
from  DW.V_ITEM_INVENTORY@dwpro  a11
where a11.QTY_ON_HAND != 0
group by  a11.ITEM_NO,
  a11.PRODUCT_DESC,
  a11.EXTENDED_DESC,
  a11.MAN_PART_NO,
  a11.MRSP,
  a11.BUYER_CODE,
  a11.STOCK_CODE,
  a11.WHS_CODE,
  a11.VENDOR_CODE,
  a11.DESCRIPTION,
  a11.cust_no,
  A11.csp_type,
  a11.currency_code,
  trim(a11.INV_GROUP)
  ) ) wims,
             (SELECT F_SURROGATE_FK,
                 CASE
                    WHEN F_CURRENCY_ID = 'US DOLLAR' THEN 'USD'
                    WHEN F_CURRENCY_ID = 'CANADIAN DOLLAR' THEN 'CAD'
                 END
                    F_CURRENCY_CD
            FROM dw.T_DIM_CURRENCY
           WHERE F_CURRENCY_ID IN ('CANADIAN DOLLAR', 'US DOLLAR')) crncy_cc,
         (SELECT F_SURROGATE_FK,
                 CASE
                    WHEN F_CURRENCY_ID = 'US DOLLAR' THEN 'CSP'
                    WHEN F_CURRENCY_ID = 'CANADIAN DOLLAR' THEN 'CSPC'
                 END
                    F_CURRENCY_CD
            FROM dw.T_DIM_CURRENCY
           WHERE F_CURRENCY_ID IN ('CANADIAN DOLLAR', 'US DOLLAR')) crncy_vc
 where TRIM(wims.F_CURRENCY_CODE) = crncy_cc.F_CURRENCY_CD(+)
         AND TRIM(wims.F_VENDOR_CODE) = crncy_vc.F_CURRENCY_CD(+);
