
SELECT a.case_id AS LOT_ID,
       '' AS SA_NUMBER,
       a.ponum AS PO_NUMBER,
       a.brand AS MANUFACTURER,
       a.model AS MODEL,
       a.serial AS SERIAL_NO,
       a.type_desc AS DESCRIPTION,
       '' AS CPU	,
       '' AS MONITOR_SIZE_INCH,
       a.disptype AS DISPOSITION,
       '' AS LEASE_SCH_NO, 	
       '' AS LESSOR_or_BMO_OWNED,
       '' AS LESSOR_RA_NO,
       '' AS RETURN_TO, 	
       '' AS RETURNING_ASSET_SUB,
       a.floorno AS FLOOR,
       a.addr1 AS ADDRESS,
       a.city2 AS CITY,
       a.prov AS PR,
       a.postcd AS POSTAL_CODE,
       a.costctr AS COST_CENTRE,
       a.recv_date AS DATE_IN,
       '' AS ASSET_PFX,
       a.asset_tag AS ASSET_TAG,
       a.warehouse AS WAREHOUSE,
       a.bmo_comments AS COMMENTS,
       '' AS PAGE_COUNT,
       '' AS LEASE_RETURN_WAYBILL_NO,
       '' AS LEASE_RETURN_SHIP_DATE
FROM DW.T_BMO_DISPOSITION a